---
title: "About"
---

Hi! I'm Jo. I'm currently a 4th year PhD student at Columbia University. I'm part of the [Social Cognitive and Affective Neuroscience Lab](https://www.ochsnerscanlab.org/) (PI: Kevin Ochsner) and [Couples Lab](https://columbiacoupleslab.weebly.com/) (PI: Niall Bolger).

I'm broadly interested in the affective nature of how we relate to other people. What explains how we feel and behave during social interactions? How do we mentally represent (close) others and our relationships to them, and what are the affective consequences of these representations? How and why do we respond to others’ emotions?

To address these questions, I enjoy learning from a variety of literatures: emotion regulation, close relationships, mentalizing, attachment, development etc. I am also curious about understanding these phenomena at the level of brain and behavior, using fMRI, intensive longitudinal methods and lab paradigms. As my interests often evolve over time, the [publications page](https://johezz.github.io/publications.html) may be helpful in offering a concrete sense of what I’ve been thinking about.

Ultimately, I hope that my work can not only inform basic science, but also contribute to interventions that can help everyone build better relationships and well-being.
