---
title: "publications"
---

# in prep

**He, Z.**, Bolger, N., Ochsner, K. (in prep) What we believe about supporting others in distress: Implications for providing regulatory support and well-being. ([scale](RBSR_Scale.pdf))

Digiovanni, A.\*, **He, Z.**\*, Ochsner, K. (under review). An integrative framework for studying social regulation of emotion.

# 2025

**He, Z.**, Vannucci, A., Meyer, M., Tottenham, N. (2025). Potential for the medial prefrontal cortex to link mentalizing and attachment schemas. [PDF](attach_mentalize.pdf)

**He, Z.**, Cohen, N., Shu, J., Bo, K., Wager, T., & Ochsner, K. (2025). Comparing the neural bases of self- and social-reappraisal, *Cerebral Cortex*, Volume 35, Issue 8 [PDF](He_et_al_2025.pdf)

# 2023

Sahi, R. S., **He, Z.**, Silvers, J. A., & Eisenberger, N. I. (2023). One size does not fit all: Decomposing the implementation and differential benefits of social emotion regulation strategies. *Emotion*, *23*(6), 1522. [https://doi.org/10.1037/emo0001194](https://psycnet.apa.org/doi/10.1037/emo0001194)
